FROM node:20.12.2 as build

# For version in healthcheck
# COPY .git/ /.git/

WORKDIR /var/app
COPY dataserver/ /var/app/
RUN yarn install
RUN yarn build-prod

FROM node:20.12.2-alpine

WORKDIR /var/app
COPY --from=build /var/app /var/app

EXPOSE 8805
CMD [ "yarn", "run", "prod" ]
