version: "3"
services:

  datastore:
    image: golosblockchain/notify:datastore
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-datastore
    volumes:
      - ./tarantool:/var/lib/tarantool

  dataserver:
    image: golosblockchain/notify:dataserver
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-dataserver
    depends_on:
      - datastore
    environment:
      NODE_URL: https://api-full.golos.id
      TARANTOOL_HOST: datastore
      SESSION_SECRET: exiKdyF+IwRIXJDmtGIl4vWUz4i3eVSISpfZoeYc0s4=
      AUTH_HOST: https://golos.app
      SITE_DOMAIN: notify.golos.app
    ports:
      - "8805:8805"
      - "8806:8806"

  # SESSION_SECRET can be generated via Node - crypto.randomBytes(32).toString('base64')