FROM node:16.1 as build

# For version in healthcheck
COPY .git/ /.git/

WORKDIR /var/app
COPY dataserver/ /var/app/
RUN yarn install
RUN yarn build-prod

FROM node:16.1-alpine

WORKDIR /var/app
COPY --from=build /var/app /var/app

EXPOSE 8805
CMD [ "yarn", "run", "prod" ]
