FROM python:3.6.5

RUN pip3 install tarantool

ENV STEEM_USER   steem
ENV STEEM_HOME   /home/steem

# TODO: need for submodule update, but it includes also datastore files
ADD . $STEEM_HOME/

RUN useradd -m $STEEM_USER && chown -R $STEEM_USER $STEEM_HOME

USER $STEEM_USER
WORKDIR $STEEM_HOME

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

ENV PATH="$STEEM_HOME/.poetry/bin:${PATH}"

RUN \
    git submodule update --init --recursive && \
    cd golos-python && \
    poetry config virtualenvs.create false && \
    poetry export -o requirements.txt && \
    pip install --user -r requirements.txt

ENV PYTHONPATH="golos-python"

CMD ["python", "./datafeed.py"]
