
-- SCOPES = {
--     'total': 0,
--     'feed': 1,
--     'delegate_vs': 2,
--     'send': 3,
--     'mention': 4,
--     'new_sponsor': 5,
--     'sponsor_inactive': 6,
--     'comment_reply': 7,
--     'subscriptions': 8,
--     'nft_token_sold': 9,
--     'message': 10,
--     'receive': 11,
--     'donate': 12,
--     'fill_order': 13,
--     'donate_msgs': 14,
--     'nft_receive': 15,
--     'referral': 16,
--     'reserved2': 17, # not used
--     'reserved3': 18, # not used
--     'reserved4': 19, # not used
--     'reserved5': 20, # not used
--     'reserved6': 21, # not used
--     'reserved7': 22, # not used
--     'reserved8': 23, # not used
--     'reserved9': 24, # not used
--     'reserved10': 25 # not used
-- }
