
-- SCOPES = {
--     'total': 0,
--     'feed': 1,
--     'delegate_vs': 2,
--     'send': 3,
--     'mention': 4,
--     'new_sponsor': 5,
--     'sponsor_inactive': 6,
--     'comment_reply': 7,
--     'subscriptions': 8,
--     'nft_token_sold': 9,
--     'message': 10,
--     'receive': 11,
--     'donate': 12,
--     'fill_order': 13,
--     'donate_msgs': 14,
--     'nft_receive': 15,
--     'referral': 16,
--     'nft_buy_offer': 17,
--     'join_request_own': 18,
--     'join_request_mod': 19,
--     'group_member_mod': 20,
--     'group_member_mem': 21,
--     'reserved7': 22,
--     'reserved8': 23,
--     'reserved9': 24, # not used
--     'reserved10': 25 # not used
-- }
