name: Build dev

on:
  push:
    branches: dev

jobs:
  datastore:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile-datastore
          push: true
          tags: vizlex/golos-ui-test:datastore
  dataserver:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile-dataserver
          push: true
          tags: vizlex/golos-ui-test:dataserver
